# Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'facial-auth-system'
    replica: '1'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Scrape configurations
scrape_configs:
  # Facial Authentication API
  - job_name: 'facial_auth_api'
    static_configs:
      - targets: ['auth_service:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL (if exporter installed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Redis (if exporter installed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  # Nginx (if exporter installed)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']

